# Generated by Django 2.0.7 on 2018-08-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20180807_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='test',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
